### ISSUE TITLE
Improve Read me to clarify installation

### ISSUE THREAD

**Issue by huwd** [MoriTanosuke/HiDPI-Steam-Skin#1]
Could you add a bit more detail to the read me about how to install these.

On Ubuntu and a 3200x1800 screen I have copied these to `~/.steam/steam/resources/styles` and it appears to have made no change?

If you can clarify so I can get it to work I'd be happy to pull request the Read me.

**Comment by MoriTanosuke** [comment]
Did you select the skin via Settings->Interface?

**Comment by huwd** [comment]
Delayed response, apologies.

There isn't the opportunity to select that from the dropdown. Mine only holds <default skin> and another i'd previously installed (air).

To be clear my process was:

`cd ~`
`git clone https://github.com/MoriTanosuke/HiDPI-Steam-Skin.git`
`cd HiDPI-Steam-Skin/resource/styles`
`cp ~/.steam/steam/resource/styles/steam.styles ~/.steam/steam/resource/styles/steam-old.styles`
`mv *.styles ~/.steam/steam/resource/styles/`

As a result no joy... could something I've overwritten elsewhere be mucking this up?
Will try and find the time to check this out from a livedisk with a fresh steam install to try and pin down any points of clash.

**Comment by MoriTanosuke** [comment]
From the file `skins_readme.txt`:

> To make a skin, you need to take a copy of `resource/styles/steam.styles` file and copy it to `skins/<your skin name here>/resource/styles/steam.styes`. The existance of that file will make Steam put that skin as an option in the _settings->interface_ dialog (Steam will need to be restarted for it to show). From there you can start editing. 
> You can put new files or existing steam files you want to replace under your skins folder. Good luck!

So I think you tried to install the theme into the wrong folder. Try to clone it into `~/.steam/steam/skins/HiDPI-Steam-Skin` directly.

I'm not on my linux system at the moment, so I can not check the path. There should already be a `skins` folder with the file `skins_readme.txt` in your directories. Maybe search for the file with `find ~/.steam -type f -name skins_readme.txt`.

**Comment by MoriTanosuke** [comment]
I updated the README as well. Will check the installation on my linux system later to confirm the steps.

**Comment by MoriTanosuke** [comment]
I just tested the installation on a fresh Xubuntu installation and enabing the skin works for me.

**Comment by huwd** [comment]
Great thanks yes, just tested myself and can confirm it works.

Only point that still differs from your readme is that my steam install path was `~/.steam/steam/skins` for some reason.

Thanks for clarifying

**Comment by MoriTanosuke** [comment]
Nice. I'll add your install path to the readme.

I noticed quite a few bugs in the skin, but at least the UI is somewhat useable on HIDPI displays.

Another great skin is Metro, http://www.metroforsteam.com. Maybe give it a try too.

**Comment by huwd** [comment]
:+1: Will do, thanks for all the work!
