### ISSUE TITLE
Different path to skins

### ISSUE THREAD

**Issue by r1b** [MoriTanosuke/HiDPI-Steam-Skin#3]
Ubuntu 15.10
Steam API v017

My skins were in:
~/.steam/steam/skins

**Comment by adojck** [comment]
In my case skins were in:
~/.local/share/Steam/skins/
Chakra OS
Steam API v017
Might need to update the readme for this Steam skin.

**Comment by MoriTanosuke** [comment]
Thanks, I added both paths to the Readme. ☺️
