### ISSUE TITLE
location of skins directory

### ISSUE THREAD

**Issue by mfiers** [MoriTanosuke/HiDPI-Steam-Skin#6]
Thanks for the theme - 

on my machine (ubuntu 1404) the skins directory needed to be in `~/.local/share/Steam/skins` - maybe update the README?

cheers
Mark

**Comment by Fuzion24** [comment]
archlinux pointed to the correct place: https://wiki.archlinux.org/index.php/HiDPI#Steam

**Comment by MoriTanosuke** [comment]
`~/.local/share/Steam/skins/` is already mentioned in the README.
